name: test 3
on:
  workflow_dispatch:

env:
  TEST_SECRET: ${{ secrets.TEST_SECRET }}

jobs:
  test3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm i
