name: test 4
on:
  workflow_dispatch:

jobs:
  test4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo $TEST_SECRET
        env:
            TEST_SECRET: ${{ secrets.TEST_SECRET }}
      - run: npm i
